services:
  productinfoviewer :
    container_name: productinfoviewer
    build: .
    ports:
    - "8501:8501"
    volumes:
    - ./modules:/app/modules
    - ./.streamlit:/app/.streamlit
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis_container
    

  redis:
    container_name: redis_container
    image: redis:latest
    ports:
    - "6379:6379"



networks:
  streamlit_network:
    external: true